name: Publish Jar to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Deploy to GitHub Packages
        run: mvn --batch-mode deploy -Dclassifier=mule-plugin -Dfile=lib/fas-json-logger-2.1.0-mule-plugin.jar -DgroupId=com.fas.mule.extensions -DartifactId=fas-json-logger -Dversion=2.1.0 -Dpackaging=jar -DgeneratePom=true
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
